### PR TITLE
sun8iw21p1: initial addition of N-BROM

### PR DESCRIPTION
**Pull request by Icenowy**
This BROM file is dumped by attaching a JTAG debugger.

Signed-off-by: Icenowy Zheng <uwu@icenowy.me>

### CODE REVIEW

**Comment by smaeul** [comment]
Can you confirm that the base address of the BROM is 0x0?

**Comment by Icenowy** [comment]
于 2022年7月5日 GMT+08:00 上午6:38:35, Samuel Holland ***@***.***> 写到:
>Can you confirm that the base address of the BROM is 0x0?

Yes, and SRAM is 0x20000.

The FEL works strangely (seems to have some coherency issue like D1)

>

**Comment by smaeul** [comment]
Thanks! Applied as 00ea7607c7439af64f8e11885e2e13476d84108c. (I fixed up the format to be accepted by `xxd -r` and added the minimal support files for ELF conversion.)

**Comment by Icenowy** [comment]
I have did some reverse engieering, but on Ghidra.

Do you have any idea that I could export the DB to this repo?

**Comment by smaeul** [comment]
For the D1 BROM, I did an XML export and used `xmlstarlet` to convert that to [the symbol list](https://github.com/smaeul/sunxi-blobs/blob/master/sun20iw1p1/rvbrom/symbols).

Or if you want, you could upload the Ghidra export directly.

**Comment by Icenowy** [comment]
I put the XML at https://gist.github.com/Icenowy/0e64ff03f48eb4c74d3ede0c10a5b802 now.

**Pull request closed without merging**
